const en = {
  appName: 'Your notes app',
  numNotRequired: 'numbers are not required',
  invalName: 'Invalid username',
  minLength: 'min length: 4 characters',
  password: 'Password',
  invalPass: 'Invalid password',
  logIn: 'Log in',
  logOut: 'Log out',
  addNote: 'Add note',
  color: 'Color',
  submit: 'Submit',
  privateText: 'Private',
  myTags: 'Tags',
  name: 'Name',
  title: 'Title',
  text: 'Text',
  sureDelete: 'Are you sure you want to delete this note?',
  confirm: 'Confirm',
  cancel: 'Cancel',
  allNotes: 'All notes',
  favorite: 'Favorite',
  changePass: 'Change Password',
  newPass: 'New Password',
}
export default en
