const ru = {
  appName: 'Ваше приложение для заметок',
  numNotRequired: 'числа не обязательны',
  invalName: 'Неправильное имя',
  minLength: 'минимальная длина: 4 символа',
  password: 'Пароль',
  invalPass: 'Неправильный пароль',
  logIn: 'Войти',
  logOut: 'Выйти',
  addNote: 'Добавить заметку',
  color: 'Цвет',
  submit: 'Подтвердить',
  prublicText: 'Публичный',
  myTags: 'теги',
  name: 'Имя',
  title: 'Название',
  text: 'Текст',
  sureDelete: 'Вы уверены что хотите удалить эту заметку?',
  confirm: 'Подтвердить',
  cancel: 'Отменить',
  allNotes: 'Все заметки',
  favorite: 'Избранное',
  changePass: 'Изменить пароль',
  newPass: 'Новый пароль',
}
export default ru
